### PR TITLE
fit blank data entry page on one pdf page

### LINKED ISSUE #19: Empty Data Entry page not overflowing properly
### Issue

Currently, when there are too many water users to fit on one pdf page, the /dataEntry 'PRINT BLANK PAGE' button does not print to multiple pages. It instead cuts off the data table, like so:
Untitled

---

### Solution

Format the jsPDF so that the table is broken into multiple if needed to print the overflow of water users

### PR DESCRIPTION
**Pull request by redraze**
### Resolves #19

---

This PR allows the entire data entry table to fit on one PDF page. The jsPDF page is correctly sized when instantiated based on the size of the image element created from the data entry table.

### CODE REVIEW

File: app/components/dataEntry/UserActions.tsx [hunk 1]
```diff
@@ -38,15 +38,20 @@ export default function UserActions(
...
-                const width = pdf.internal.pageSize.getWidth() * .95;
-                pdf.addImage(img, 'JPEG', 10, 10, width, 0);
+                
+                const pdf = new jsPDF({
+                    orientation: "landscape",
+                    unit: "px",
+                    format: [img.width, img.height]
+                });
+                
+                const xBuffer = img.width * 0.05 - 1;
```
Comment (redraze) [inline app/components/dataEntry/UserActions.tsx:50]: specify why these two buffer values have 1 subtracted from them
